Repository pshn111/tictactoe, pull requests merged in 2019-01, with the labels that each got.

#5 Create .gitignore
  .gitignore
Labels: repository preparation

#6 Add feature1: tie check
  src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
  src/main/java/cs/ualberta/cmput402/tictactoe/board/Board.java
Labels: feature1: tie check

#11 Add feature2: scoreboard
  src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
Labels: feature2: scoreboard

#12 Add feature3: play again
  src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
Labels: feature3: play again

#14 Fix no prompt message is shown after receiving an invalid input for play again feature
  src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
Labels: bug

#16 Address code review
  src/main/java/cs/ualberta/cmput402/tictactoe/TicTacToeGame.java
Labels: Feedback
